In [ ]:
import pandas as pd
import hashlib
from datetime import datetime

CSV_PATH = r"d:\intern\pbb\31111-0120_en_flat.csv"#change the path if u want to run it

df = pd.read_csv(CSV_PATH, sep=";", dtype=str)
print(f"Total rows: {len(df)}")
df.head(2)

Total rows: 177408

,statistics_code,statistics_label,time_code,time_label,time,1_variable_code,1_variable_label,1_variable_attribute_code,1_variable_attribute_label,2_variable_code,...,4_variable_attribute_label,5_variable_code,5_variable_label,5_variable_attribute_code,5_variable_attribute_label,value,value_unit,value_variable_code,value_variable_label,value_q
0,31111,Statistics of building permits,JAHR,Year,2026,MONAT,Months,MONAT08,August,DLAND,...,Construction of new buildings,BAUGB1,Type of building,GBD-NW-NLW-FW,Factory and workshop buildings,...,number,BAU016,Buildings / reconstruction projects,NaN
1,31111,Statistics of building permits,JAHR,Year,2026,MONAT,Months,MONAT08,August,DLAND,...,Construction of new buildings,BAUGB1,Type of building,GBD-NW-NLW-FW,Factory and workshop buildings,...,1000 cu m,FLC003,Volume constructed,NaN

In [3]:
# Explore key dimension values
print("=== Construction activity codes (4_variable_attribute_code = BAUTK1) ===")
print(df["4_variable_attribute_code"].value_counts().to_string())

print("\n=== Building type codes (5_variable_attribute_code = BAUGB1) ===")
print(df["5_variable_attribute_code"].value_counts().to_string())

print("\n=== Metric codes (value_variable_code) ===")
print(df["value_variable_code"].value_counts().to_string())

=== Construction activity codes (4_variable_attribute_code = BAUTK1) ===
4_variable_attribute_code
BTK-GEB-NEU    59136
BTK-GEB-BST    59136
BTK-GEB        59136

=== Building type codes (5_variable_attribute_code = BAUGB1) ===
5_variable_attribute_code
GBD-NW-NLW-FW    6336
GBD-W-WO1-WO2    6336
GBD-NW-IFS       6336
GBD-W-WH         6336
GBD-NW-NLW-HL    6336
GBD-NW-NLW-WL    6336
GBD-NW-NLW       6336
GBD-NW-IFS-BW    6336
GBD-W-ETW        6336
GBD-NW-IFS-FS    6336
GBD-W-WO2        6336
GBD-NW           6336
GBD-NW-IFS-SW    6336
GBD-NW-S         6336
GBD-W-WO1        6336
GBD-NW-IFS-GS    6336
GBD-NW-NLW-HG    6336
GBD-NW-BV        6336
GBD-W-NW         6336
GBD-NW-LW        6336
GBD-NW-NLW-H     6336
GBD-W-WO3UM      6336
GBD-NW-AN        6336
GBD-NW-IFS-KU    6336
GBD-NW-IFS-VE    6336
GBD-NW-IFS-VN    6336
GBD-NW-IFS-SO    6336
GBD-W            6336

=== Metric codes (value_variable_code) ===
value_variable_code
BAU016    16128
FLC003    16128
WOHN08    16128
WOE009    16128
FLC002    16128
BAU015    16128
BAU003    16128
FLC015    16128
WOHN01    16128
VKB001    16128
FLC014    16128

In [4]:
def normalize_destatis_31111(df_raw: pd.DataFrame, file_hash: str) -> pd.DataFrame:
    """
    Filter and normalize Destatis 31111 flat CSV into a warehouse-ready long table.
    Selects: residential new-build dwelling permits (WOHN01) by Bundesland, monthly.

    Key column mapping (flat CSV format):
      time                        -> year (e.g. "2026")
      1_variable_attribute_code   -> month code (e.g. "MONAT08")
      2_variable_attribute_code   -> Bundesland AGS code (e.g. "16")
      2_variable_attribute_label  -> Bundesland name (e.g. "Thüringen")
      4_variable_attribute_code   -> construction activity (BTK-GEB-NEU = new build)
      5_variable_attribute_code   -> building type (GBD-W-* = residential)
      value_variable_code         -> metric (WOHN01 = dwellings, BAU016 = buildings, etc.)
      value                       -> raw value string (number, "...", "-", "x")
      value_unit                  -> unit string (e.g. "number", "1000 sq m")
    """
    # Filter: new construction + residential building types + dwelling count metric
    mask = (
        (df_raw["4_variable_attribute_code"] == "BTK-GEB-NEU") &
        (df_raw["5_variable_attribute_code"].str.startswith("GBD-W")) &
        (df_raw["value_variable_code"] == "WOHN01")
    )
    f = df_raw[mask].copy()

    # Combine year + month code into ISO 8601 period (e.g. "MONAT08" -> "2026-08")
    month_num = f["1_variable_attribute_code"].str.extract(r"MONAT(\d+)")[0].str.zfill(2)
    f["time_period"] = f["time"].str.strip() + "-" + month_num

    # Region: zero-pad AGS code to 2 digits
    f["region_code"] = f["2_variable_attribute_code"].str.strip().str.zfill(2)
    f["region_name"] = f["2_variable_attribute_label"].str.strip()

    # Building type dimension (e.g. GBD-W-WO1-WO2, GBD-W-MFH)
    f["building_type_code"]  = f["5_variable_attribute_code"].str.strip()
    f["building_type_label"] = f["5_variable_attribute_label"].str.strip()

    # Metric provenance
    f["source_variable"]       = f["value_variable_code"].str.strip()
    f["source_variable_label"] = f["value_variable_label"].str.strip()
    f["unit"]                  = f["value_unit"].str.strip()

    # Quality flags for non-numeric values
    # "..." = future placeholder  |  "-", "x", "." = suppressed/confidential
    raw = f["value"].str.strip()
    f["quality_flag"] = "ok"
    f.loc[raw.isin({"-", "x", ".", "/"}), "quality_flag"] = "suppressed"
    f.loc[raw == "...",                    "quality_flag"] = "future"

    numeric_raw = raw.where(f["quality_flag"] == "ok", other=pd.NA)
    f["value_numeric"] = pd.to_numeric(numeric_raw, errors="coerce")

    # Provenance columns (warehouse traceability requirement)
    f["provider"]            = "destatis"
    f["source_table"]        = "31111-0120"
    f["ingestion_timestamp"] = datetime.utcnow().strftime("%Y-%m-%dT%H:%M:%SZ")
    f["file_hash"]           = file_hash

    return f[[
        "provider", "source_table", "source_variable", "source_variable_label",
        "region_code", "region_name", "building_type_code", "building_type_label",
        "time_period", "value_numeric", "unit", "quality_flag",
        "ingestion_timestamp", "file_hash",
    ]].reset_index(drop=True)


# Hash the source file for provenance tracking
with open(CSV_PATH, "rb") as fh:
    file_hash = hashlib.md5(fh.read()).hexdigest()

normalized = normalize_destatis_31111(df, file_hash)
print(f"Rows after filter: {len(normalized)}")
normalized.head(10)

Rows after filter: 1536

,provider,source_table,source_variable,source_variable_label,region_code,region_name,building_type_code,building_type_label,time_period,value_numeric,unit,quality_flag,ingestion_timestamp,file_hash
0,destatis,31111-0120,WOHN01,Dwellings,11,Berlin,GBD-W-WO3UM,Residential buildings with 3 or more dwellings,2026-12,NaN,number,future,2026-06-01T11:43:46Z,666d833edbfa0c3e54ba1cf5083766dd
1,destatis,31111-0120,WOHN01,Dwellings,13,Mecklenburg-Vorpommern,GBD-W-NW,Residential and non-residential buildings,2026-01,404.0,number,ok,2026-06-01T11:43:46Z,666d833edbfa0c3e54ba1cf5083766dd
2,destatis,31111-0120,WOHN01,Dwellings,11,Berlin,GBD-W-WO3UM,Residential buildings with 3 or more dwellings,2026-11,NaN,number,future,2026-06-01T11:43:46Z,666d833edbfa0c3e54ba1cf5083766dd
3,destatis,31111-0120,WOHN01,Dwellings,01,Schleswig-Holstein,GBD-W-WO2,Residential buildings with 2 dwellings,2026-09,NaN,number,future,2026-06-01T11:43:46Z,666d833edbfa0c3e54ba1cf5083766dd
4,destatis,31111-0120,WOHN01,Dwellings,08,Baden-Württemberg,GBD-W-WO3UM,Residential buildings with 3 or more dwellings,2026-12,NaN,number,future,2026-06-01T11:43:46Z,666d833edbfa0c3e54ba1cf5083766dd
5,destatis,31111-0120,WOHN01,Dwellings,08,Baden-Württemberg,GBD-W-WO3UM,Residential buildings with 3 or more dwellings,2026-11,NaN,number,future,2026-06-01T11:43:46Z,666d833edbfa0c3e54ba1cf5083766dd
6,destatis,31111-0120,WOHN01,Dwellings,01,Schleswig-Holstein,GBD-W-WO2,Residential buildings with 2 dwellings,2026-07,NaN,number,future,2026-06-01T11:43:46Z,666d833edbfa0c3e54ba1cf5083766dd
7,destatis,31111-0120,WOHN01,Dwellings,13,Mecklenburg-Vorpommern,GBD-W-NW,Residential and non-residential buildings,2026-05,NaN,number,future,2026-06-01T11:43:46Z,666d833edbfa0c3e54ba1cf5083766dd
8,destatis,31111-0120,WOHN01,Dwellings,08,Baden-Württemberg,GBD-W-WO3UM,Residential buildings with 3 or more dwellings,2026-10,NaN,number,future,2026-06-01T11:43:46Z,666d833edbfa0c3e54ba1cf5083766dd
9,destatis,31111-0120,WOHN01,Dwellings,01,Schleswig-Holstein,GBD-W-WO2,Residential buildings with 2 dwellings,2026-08,NaN,number,future,2026-06-01T11:43:46Z,666d833edbfa0c3e54ba1cf5083766dd

In [5]:
# ── Validation checks ─────────────────────────────────────────────────────────
# NOTE on building-type hierarchy:
#   GBD-W         = all residential buildings (aggregate of WO1, WO2, WO3UM, WH)
#   GBD-W-WO1-WO2 = 1-or-2-family homes (aggregate of WO1 + WO2)
#   GBD-W-WO1     = single-family
#   GBD-W-WO2     = two-family
#   GBD-W-WO3UM   = 3+ dwelling buildings
#   GBD-W-WH      = residential establishments
#   GBD-W-NW      = mixed residential+non-residential (separate category, not in GBD-W)
#   GBD-W-ETW     = owner-occupied dwellings (cross-cuts GBD-W sub-types)
# Summing all 8 rows would double-count. Use building_type_code == "GBD-W" for
# the canonical aggregate; keep granular sub-types for drill-down analysis.

ok = normalized[normalized["quality_flag"] == "ok"]

# 1. Completeness: Bundesländer per month (using aggregate GBD-W only)
agg = ok[ok["building_type_code"] == "GBD-W"]
coverage = agg.groupby("time_period")["region_code"].nunique()
incomplete = coverage[coverage < 16]
print(f"Months with < 16 states (GBD-W aggregate): {len(incomplete)} out of {len(coverage)}")

# 2. No negative values
print(f"Negative values: {(ok['value_numeric'] < 0).sum()}")

# 3. Quality flag breakdown
print("\nQuality flag distribution:")
print(normalized["quality_flag"].value_counts().to_string())

# 4. Month-on-month spike detection on GBD-W aggregate (> ±80%)
agg2 = agg.sort_values(["region_code", "time_period"])
agg2["mom_pct"] = agg2.groupby("region_code")["value_numeric"].pct_change() * 100
spikes = agg2[agg2["mom_pct"].abs() > 80]
print(f"\nMonth-on-month spikes >±80% (GBD-W): {len(spikes)} rows")
if not spikes.empty:
    print(spikes[["time_period","region_name","value_numeric","mom_pct"]].to_string())

# 5. Latest month — canonical aggregate (GBD-W = pure residential buildings only)
latest_month = agg["time_period"].max()
print(f"\n── Latest available month: {latest_month} ──")
print("New residential dwelling permits, pure residential buildings (GBD-W):")
summary = (agg[agg["time_period"] == latest_month]
           .groupby(["region_code","region_name"])["value_numeric"].sum()
           .reset_index().sort_values("value_numeric", ascending=False))
print(summary.to_string(index=False))

Months with < 16 states (GBD-W aggregate): 0 out of 3
Negative values: 0

Quality flag distribution:
quality_flag
future        1152
ok             363
suppressed      21

Month-on-month spikes >±80% (GBD-W): 4 rows
     time_period         region_name  value_numeric     mom_pct
742      2026-03  Schleswig-Holstein         1146.0   99.304348
1045     2026-02              Bremen          259.0  212.048193
853      2026-02             Sachsen         1731.0  319.128329
186      2026-03           Thüringen          140.0   84.210526

── Latest available month: 2026-03 ──
New residential dwelling permits, pure residential buildings (GBD-W):
region_code            region_name  value_numeric
         09                 Bayern         3859.0
         05    Nordrhein-Westfalen         2320.0
         08      Baden-Württemberg         2166.0
         03          Niedersachsen         1898.0
         11                 Berlin         1450.0
         01     Schleswig-Holstein         1146.0
         06                 Hessen          891.0
         12            Brandenburg          777.0
         07        Rheinland-Pfalz          730.0
         02                Hamburg          548.0
         14                Sachsen          397.0
         13 Mecklenburg-Vorpommern          334.0
         15         Sachsen-Anhalt          225.0
         04                 Bremen          203.0
         16              Thüringen          140.0
         10               Saarland          113.0

In [6]:
normalized.to_excel(r"d:\intern\pbb\normalized_permits.xlsx", index=False)
print("Done")

Done

In [ ]:
# ── Layer 3: Canonical ────────────────────────────────────────────────────────
# Filter normalized to GBD-W aggregate (pure residential) with quality_flag=ok, map to canonical variable name

canonical = normalized[
    (normalized["building_type_code"] == "GBD-W") &
    (normalized["quality_flag"] == "ok")
].copy()

canonical["canonical_variable"] = "regional_building_permits_residential_new"

# YoY: year-on-year change (requires ≥13 months of history; only 3 months available, so all NaN is expected)

canonical = canonical.sort_values(["region_code", "time_period"]).reset_index(drop=True)
canonical["yoy_pct"] = (
    canonical
    .groupby("region_code")["value_numeric"]
    .pct_change(periods=12) * 100
)

print(f"Canonical rows: {len(canonical)}")
canonical[["region_code", "region_name", "time_period",
           "canonical_variable", "value_numeric", "yoy_pct"]].head(10)

Canonical rows: 48

,region_code,region_name,time_period,canonical_variable,value_numeric,yoy_pct
0,01,Schleswig-Holstein,2026-01,regional_building_permits_residential_new,775.0,NaN
1,01,Schleswig-Holstein,2026-02,regional_building_permits_residential_new,575.0,NaN
2,01,Schleswig-Holstein,2026-03,regional_building_permits_residential_new,1146.0,NaN
3,02,Hamburg,2026-01,regional_building_permits_residential_new,299.0,NaN
4,02,Hamburg,2026-02,regional_building_permits_residential_new,487.0,NaN
5,02,Hamburg,2026-03,regional_building_permits_residential_new,548.0,NaN
6,03,Niedersachsen,2026-01,regional_building_permits_residential_new,2253.0,NaN
7,03,Niedersachsen,2026-02,regional_building_permits_residential_new,1998.0,NaN
8,03,Niedersachsen,2026-03,regional_building_permits_residential_new,1898.0,NaN
9,04,Bremen,2026-01,regional_building_permits_residential_new,83.0,NaN

In [ ]:
# ── Layer 4: Application view ─────────────────────────────────────────────────
#Latest month KPI by Bundesland


latest_month = canonical["time_period"].max()

app_kpi_map = (
    canonical[canonical["time_period"] == latest_month]
    [["region_code", "region_name", "time_period", "value_numeric", "yoy_pct"]]
    .rename(columns={"value_numeric": "permits_count"})
    .sort_values("permits_count", ascending=False)
    .reset_index(drop=True)
)

print(f"Layer 4 — KPI map for {latest_month}")
app_kpi_map

Layer 4 — KPI map for 2026-03

   region_code             region_name time_period  permits_count  yoy_pct
0           09                  Bayern     2026-03         3859.0      NaN
1           05     Nordrhein-Westfalen     2026-03         2320.0      NaN
2           08       Baden-Württemberg     2026-03         2166.0      NaN
3           03           Niedersachsen     2026-03         1898.0      NaN
4           11                  Berlin     2026-03         1450.0      NaN
5           01      Schleswig-Holstein     2026-03         1146.0      NaN
6           06                  Hessen     2026-03          891.0      NaN
7           12             Brandenburg     2026-03          777.0      NaN
8           07         Rheinland-Pfalz     2026-03          730.0      NaN
9           02                 Hamburg     2026-03          548.0      NaN
10          14                 Sachsen     2026-03          397.0      NaN
11          13  Mecklenburg-Vorpommern     2026-03          334.0      NaN
12          15          Sachsen-Anhalt     2026-03          225.0      NaN
13          04                  Bremen     2026-03          203.0      NaN
14          16               Thüringen     2026-03          140.0      NaN
15          10                Saarland     2026-03          113.0      NaN

In [ ]:
# Save outputs (Layer 2 / 3 / 4)
normalized.to_parquet(r"d:\intern\pbb\layer2_normalized.parquet", index=False)
canonical.to_parquet( r"d:\intern\pbb\layer3_canonical.parquet",  index=False)
app_kpi_map.to_excel( r"d:\intern\pbb\layer4_kpi.xlsx",           index=False)
print("Files saved.")

# Load into PostgreSQL (requires a live database instance —示意 only)

# engine = sqlalchemy.create_engine(
#     "postgresql://username:pwd@localhost:5432/db"
# )
# normalized.to_sql("layer2_normalized", engine, if_exists="append", index=False)
# canonical.to_sql( "layer3_canonical",  engine, if_exists="append", index=False)
# app_kpi_map.to_sql("layer4_kpi_map",   engine, if_exists="replace", index=False)

Files saved.